Repository microsoft/mu_silicon_arm_tiano, pull requests merged in 2022-12, with the labels that each got.

#32 Add logic for container build to Matrix-Build-Job.yml
  .azurepipelines/Matrix-Build-Job.yml
Labels: impact:non-functional

#38 ArmGicLib/ArmGicV3: Update ICC_SG1R register
  ArmPkg/Drivers/ArmGic/GicV3/AArch64/ArmGicV3.masm
Labels: type:bug, impact:non-functional

#41 Cherry-pick NorFlashBlockIoDxe.c debug macro fix to release/202202
  ArmPlatformPkg/Drivers/NorFlashDxe/NorFlashBlockIoDxe.c
Labels: type:bug
