Repository microsoft/mu_silicon_arm_tiano, pull requests merged in 2024-10, with the labels that each got.

#281 [CHERRY-PICK] [REBASE & FF] Revert Mu Commit in Favor of edk2 Commit
  ArmPkg/Drivers/CpuDxe/CpuMmuCommon.c
Labels: impact:non-functional

#292 ArmPkg: Remove pragma pack from CpuDxe
  ArmPkg/Drivers/CpuDxe/PageTableMemoryAllocation.c
Labels: type:bug, impact:non-functional

#294 [REBASE & FF] ArmPkg: Remove pragma pack from CpuDxe
  ArmPkg/Drivers/CpuDxe/PageTableMemoryAllocation.c
Labels: type:bug, impact:non-functional

#295 ArmPkg: Fix call to BuildCpuHob in CpuPei.c
  ArmPkg/Drivers/CpuPei/CpuPei.c
Labels: impact:non-functional

#296 [REBASE & FF] ArmPkg: Fix call to BuildCpuHob in CpuPei.c
  ArmPkg/Drivers/CpuPei/CpuPei.c
Labels: impact:non-functional

#298 ArmPkg: CpuDxe: Fix Bad Cast
  ArmPkg/Drivers/CpuDxe/AArch64/Mmu.c
Labels: type:bug

#303 Revert "ArmPkg: GICv3: Fix ARM_GICD_IROUTER incorrect writes for SPIs"
  ArmPkg/Drivers/ArmGic/GicV3/ArmGicV3Dxe.c
  ArmPkg/Include/Library/ArmGicLib.h
Labels: impact:breaking-change, impact:non-functional
