Repository microsoft/mu_silicon_arm_tiano, pull requests merged in 2024-07, with the labels that each got.

#239 [Rebase & FF] 202405: ArmPkg: PlatformBootManagerLib: Add missing function required by MU
  ArmPkg/Library/PlatformBootManagerLib/PlatformBm.c
Labels: impact:non-functional

#252 ArmPkg: ArmPsciMpServicesDxe: Fix CPU resource leakage
  ArmPkg/Drivers/ArmPsciMpServicesDxe/ArmPsciMpServicesDxe.c
Labels: type:bug

#254 ArmVirtPkg: Fix MarkdownLint issues in Readme
  ArmVirtPkg/PlatformCI/ReadMe.md
Labels: impact:non-functional, type:documentation

#253 ArmVirtPkg: QemuVirtMemInfoPeiLib: Allow PcdSystemMemorySize to be non-fixed
  ArmVirtPkg/Library/QemuVirtMemInfoLib/QemuVirtMemInfoPeiLib.inf
Labels: impact:non-functional

#258 Set PciFunction to 0xFFFF for _PRT per specification
  DynamicTablesPkg/Library/Acpi/Arm/AcpiSsdtPcieLibArm/SsdtPcieGenerator.c
Labels: impact:non-functional

#260 [Squash on Rebase] ArmPkg: Update ExceptionSupport.masm
  ArmPkg/Library/ArmExceptionLib/AArch64/ExceptionSupport.masm
  ArmPkg/Library/ArmExceptionLib/ArmRelocateExceptionLib.inf
Labels: impact:non-functional
