Repository microsoft/mu_silicon_arm_tiano, pull requests merged in 2024-01, with the labels that each got.

#194 .git-blame-ignore-revs: Ignore Line Ending and Uncrustify only commits
  .git-blame-ignore-revs
Labels: impact:non-functional, semver:patch

#195 Updated CISettings.py to use the edk2toolext codeql helpers
  .github/workflows/codeql.yml
  .pytool/CISettings.py
Labels: impact:non-functional, impact:testing

#196 Added a few additional functions to MSFT version of AArch64Support ass…
  ArmPkg/Library/ArmLib/AArch64/AArch64Support.masm
Labels: complexity:easy, impact:non-functional
