Repository microsoft/mu_silicon_arm_tiano, pull requests merged in 2024-11, with the labels that each got.

#305 StandaloneMmPkg: Arm/StandaloneMmCoreEntryPoint Remove Check for SMC ID
  ArmPkg/Library/StandaloneMmCoreEntryPoint/Arm/StandaloneMmCoreEntryPoint.c
Labels: type:backport

#306 [CHERRY-PICK] DynamicTablesPkg: AmlLib: Fix CodeQL Issue
  DynamicTablesPkg/Library/Common/AmlLib/AmlEncoding/Aml.c
Labels: impact:non-functional, type:backport

#314 [SQUASH] Revert "ArmPkg: SmmVariablePei: Introduce variable read service in PEI"
  ArmPkg/ArmPkg.dsc
  ArmPkg/Drivers/SmmVariablePei/SmmVariablePei.c
  ArmPkg/Drivers/SmmVariablePei/SmmVariablePei.h
  ArmPkg/Drivers/SmmVariablePei/SmmVariablePei.inf
Labels: impact:breaking-change, type:backport
