Repository microsoft/mu_silicon_arm_tiano, pull requests merged in 2025-05, with the labels that each got.

#377 PSCI warm reset fix
  ArmPkg/Library/ArmPsciResetSystemLib/ArmPsciResetSystemLib.c
  ArmPkg/Library/ArmPsciResetSystemLib/ArmPsciResetSystemLib.inf
Labels: type:backport

#374 Add RMR support for IORT and SmmuDxe IoMmu mappings
  ArmPkg/Drivers/SmmuDxe/IoMmu.c
  ArmPkg/Drivers/SmmuDxe/IoMmu.h
  ArmPkg/Drivers/SmmuDxe/SmmuDxe.c
  ArmPkg/Drivers/SmmuDxe/SmmuV3.h
  ArmPkg/Drivers/SmmuDxe/SmmuV3Util.c
Labels: impact:security

#379 Using proper bitmask and shift for NoAccess functions
  ArmPkg/Library/StandaloneMmMmuLib/ArmMmuStandaloneMmLib.c
Labels: type:bug
