Repository microsoft/mu_silicon_arm_tiano, pull requests merged in 2025-04, with the labels that each got.

#359 [Rebase & FF] Revert UUID mangling change from MU
  ArmPkg/Library/ArmFfaLib/ArmFfaCommon.c
Labels: impact:breaking-change

#362 [Squash on Rebase] DefaultExceptionHandler: Remove MU_CHANGE casting AARCH64 ESR from a …
  ArmPkg/Library/DefaultExceptionHandlerLib/AArch64/DefaultExceptionHandler.c
Labels: impact:non-functional, type:backport

#365 Run CI using release branches of dependent repos
  .pytool/CISettings.py
Labels: impact:non-functional

#367 [SQUASH ON REBASE] Support Concatenated Translation Tables
  ArmPkg/Drivers/SmmuDxe/IoMmu.c
  ArmPkg/Drivers/SmmuDxe/SmmuDxe.c
  ArmPkg/Drivers/SmmuDxe/SmmuV3.h
  ArmPkg/Drivers/SmmuDxe/SmmuV3Util.c
Labels: impact:security
